nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.0.0-rc.1.cjs

packageExtensions:
  jest-playwright-preset@^1.0.0:
    dependencies:
      playwright: ^1.0.0
  gatsby-plugin-mdx@^2.0.0:
    peerDependencies:
      gatsby-remark-images: ^5.0.0
  gatsby@^3.0.0:
    dependencies:
      babel-plugin-styled-components: ^1.0.0
  styled-components@^5.0.0:
    dependencies:
      react-is: '*'
      babel-plugin-macros: ^3.0.0

pnpFallbackMode: all
