nodeLinker: pnp

packageExtensions:
  gatsby@^4.0.0:
    dependencies:
      babel-plugin-styled-components: ^2.0.0
  jest-playwright-preset@^1.0.0:
    dependencies:
      jest-environment-node: ^27.0.0
      jest-runner: ^27.0.0
      playwright: ^1.0.0
  styled-components@^5.0.0:
    dependencies:
      react-is: '*'
  chalk@^5.0.0:
    dependencies:
      '#ansi-styles': npm:ansi-styles@^6.0.0
      '#supports-color': npm:supports-color@^9.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.2.1.cjs
