nodeLinker: pnp

packageExtensions:
  chalk@^5.0.0:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@^6.0.0"
      "#supports-color": "npm:supports-color@^9.0.0"
  gatsby@^5.0.0:
    dependencies:
      babel-plugin-styled-components: ^2.0.0
  jest-playwright-preset@^3.0.0:
    dependencies:
      jest-environment-node: ^29.0.0
      jest-runner: ^29.0.0
      playwright: ^1.0.0
  styled-components@^5.0.0:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.5.0.cjs
