nodeLinker: pnp

packageExtensions:
  gatsby@^3.0.0:
    dependencies:
      babel-plugin-styled-components: ^1.0.0
  gatsby-plugin-mdx@^2.0.0:
    dependencies:
      mkdirp: ^1.0.0
  jest-playwright-preset@^1.0.0:
    dependencies:
      jest-environment-node: ^27.0.0
      jest-runner: ^27.0.0
      playwright: ^1.0.0
  styled-components@^5.0.0:
    dependencies:
      babel-plugin-macros: ^3.0.0
      react-is: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.0.2.cjs
