name: Deploy Docs
on:
  push:
    branches: [main, docs-live, docs-beta]
  workflow_dispatch:
    inputs:
      docsEnv:
        description: 'Docs Environment'
        required: true
        default: 'dev'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build component
        run: npm run build
      - name: Build docs
        run: npm run build-docs
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Dev - Deploy
        if: ${{ (github.event.inputs.docsEnv == 'dev' || github.ref == 'refs/heads/docs-beta') && success() }}
        run: sh ./.github/scripts/docs-deploy.sh
        env:
          S3_BUCKET: ${{ secrets.DOCS_DEV_BUCKET }}
          CLOUDFRONT_ID: ${{ secrets.DOCS_DEV_CLOUDFRONT }}
      - name: Live - Deploy
        if: ${{ (github.event.inputs.docsEnv == 'live' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/docs-live') && success() }}
        run: sh ./.github/scripts/docs-deploy.sh
        env:
          S3_BUCKET: ${{ secrets.DOCS_LIVE_BUCKET }}
          CLOUDFRONT_ID: ${{ secrets.DOCS_LIVE_CLOUDFRONT }}
