name: Test
on:
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright dependencies
        run: npx playwright install --with-deps
      - name: Build
        run: npm run build
      - name: Unit Tests
        run: npm run test
      - name: Integration Tests
        run: npm run integration-test
      - name: Test React 19
        run: npm run browser-test-19
      - name: Test React 18
        run: npm run browser-test-18
      - name: Test React 17
        run: npm run browser-test-17
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/browser-test/playwright-report/
          retention-days: 30
