name: Test
on:
  pull_request:
    branches: [main]
jobs:
  core-tests:
    name: Core Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Typescript check
        run: npm run tsc
      - name: Lint check
        run: npm run lint
      - name: Unit Tests
        run: npm run test
      - name: Integration Tests
        run: npm run integration-test

  browser-tests:
    name: Browser Tests (React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    needs: core-tests
    strategy:
      matrix:
        react-version: [17, 18, 19]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright dependencies
        run: npx playwright install --with-deps
      - name: Build
        run: npm run build
      - name: Test React ${{ matrix.react-version }}
        run: npm run browser-test-${{ matrix.react-version }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-react-${{ matrix.react-version }}
          path: packages/browser-test/playwright-report/
          retention-days: 30
